import type {Vec2} from '../core/types';
import type {
  Renderer,
  RendererOptions,
  TransformOptions,
} from './renderer-interface';

function formatTransform(t: string | TransformOptions): string {
  if (typeof t === 'string') {
    return t;
  }
  const parts = [];
  if (t.translate) {
    parts.push(`translate(${t.translate.x}, ${t.translate.y})`);
  }
  if (t.rotate) {
    const rx = t.rotate.cx !== undefined ? `, ${t.rotate.cx}` : '';
    const ry = t.rotate.cy !== undefined ? `, ${t.rotate.cy}` : '';
    parts.push(`rotate(${t.rotate.angle}${rx}${ry})`);
  }
  return parts.join(' ');
}

export class SVGRenderer implements Renderer {
  private elements: string[] = [];
  private minX = 0;
  private minY = 0;
  private width = 0;
  private height = 0;

  begin(minX: number, minY: number, width: number, height: number): void {
    this.minX = minX;
    this.minY = minY;
    this.width = width;
    this.height = height;
    this.elements = [];

    // Add SVG background matching app canvas theme
    this.elements.push(
      `<rect x="${minX}" y="${minY}" width="${width}" height="${height}" fill="#1e2028" />`,
    );
  }

  end(): string {
    return [
      '<?xml version="1.0" encoding="utf-8"?>',
      '<!-- Generated by 2D Architectural Plan Editor -->',
      `<svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="${this.minX} ${this.minY} ${this.width} ${this.height}" width="100%" height="100%">`,
      ...this.elements,
      '</svg>',
    ].join('\n');
  }

  pushGroup(options?: {transform?: string | TransformOptions}): void {
    const attrs = [];
    if (options?.transform) {
      attrs.push(`transform="${formatTransform(options.transform)}"`);
    }
    this.elements.push(`  <g ${attrs.join(' ')}>`);
  }

  popGroup(): void {
    this.elements.push('  </g>');
  }

  private buildAttrs(options?: RendererOptions): string {
    if (!options) return '';
    const attrs = [];
    if (options.fill) attrs.push(`fill="${options.fill}"`);
    if (options.stroke) attrs.push(`stroke="${options.stroke}"`);
    if (options.strokeWidth !== undefined)
      attrs.push(`stroke-width="${options.strokeWidth}"`);
    if (options.strokeDasharray)
      attrs.push(`stroke-dasharray="${options.strokeDasharray}"`);
    if (options.fontFamily) attrs.push(`font-family="${options.fontFamily}"`);
    if (options.fontWeight) attrs.push(`font-weight="${options.fontWeight}"`);
    if (options.fontSize !== undefined)
      attrs.push(`font-size="${options.fontSize}"`);
    if (options.textAnchor) attrs.push(`text-anchor="${options.textAnchor}"`);
    if (options.dominantBaseline)
      attrs.push(`dominant-baseline="${options.dominantBaseline}"`);
    return attrs.join(' ');
  }

  drawRect(
    x: number,
    y: number,
    width: number,
    height: number,
    options?: RendererOptions,
  ): void {
    this.elements.push(
      `  <rect x="${x}" y="${y}" width="${width}" height="${height}" ${this.buildAttrs(options)} />`,
    );
  }

  drawPolygon(points: Vec2[], options?: RendererOptions): void {
    const pts = points.map((p) => `${p.x},${p.y}`).join(' ');
    this.elements.push(
      `  <polygon points="${pts}" ${this.buildAttrs(options)} />`,
    );
  }

  drawLine(p1: Vec2, p2: Vec2, options?: RendererOptions): void {
    this.elements.push(
      `  <line x1="${p1.x}" y1="${p1.y}" x2="${p2.x}" y2="${p2.y}" ${this.buildAttrs(options)} />`,
    );
  }

  drawCircle(center: Vec2, radius: number, options?: RendererOptions): void {
    this.elements.push(
      `  <circle cx="${center.x}" cy="${center.y}" r="${radius}" ${this.buildAttrs(options)} />`,
    );
  }

  drawArc(
    center: Vec2,
    radius: number,
    startAngle: number,
    endAngle: number,
    counterClockwise: boolean,
    options?: RendererOptions,
  ): void {
    const startX = center.x + radius * Math.cos(startAngle);
    const startY = center.y + radius * Math.sin(startAngle);
    const endX = center.x + radius * Math.cos(endAngle);
    const endY = center.y + radius * Math.sin(endAngle);
    const largeArc = Math.abs(endAngle - startAngle) > Math.PI ? 1 : 0;
    const sweep = counterClockwise ? 0 : 1;

    this.elements.push(
      `  <path d="M ${startX} ${startY} A ${radius} ${radius} 0 ${largeArc} ${sweep} ${endX} ${endY}" ${this.buildAttrs(options)} />`,
    );
  }

  drawText(
    text: string,
    position: Vec2,
    options?: RendererOptions,
    transform?: string | TransformOptions,
  ): void {
    const attrStr = this.buildAttrs(options);
    const transformStr = transform
      ? ` transform="${formatTransform(transform)}"`
      : '';
    this.elements.push(
      `  <text x="${position.x}" y="${position.y}" ${attrStr}${transformStr}>${text}</text>`,
    );
  }
}
